### ISSUE TITLE
How to turn number into classification?

### ISSUE THREAD

**Issue by keyuchen21** [punyajoy/HateXplain#10]
After apply this model, I got scores for Hate, Offensive and Normal, How can I turn it into classification as Hate/Offensive/Normal?

Is there a cutoff point?

**Comment by punyajoy** [comment]
Hi @km5ar, the number depends on the application you are planning. The best strategy will be to evaluate f1 score/accuracy with different confidence scores in the target domain and annotate 100-200 samples. That will help you fix the cutoff.
