### ISSUE TITLE
machine capacity used

### ISSUE THREAD

**Issue by pharaon-dev** [punyajoy/HateXplain#12]
Hello, What is the capacity of the machine used (Ram) to training the model ?
I need advice on a platform that I could use to train the model taking into account the requirements.
I can't create a virtual environment on kaggle to take into account the requirements.

**Comment by punyajoy** [comment]
you can use google colaboratory. The RAM  should be enough or else you can change the batch size

**Comment by punyajoy** [comment]
python version 3.7

**Comment by pharaon-dev** [comment]
What is version of python used ?

Le lun. 13 juin 2022 à 10:20, Punyajoy Saha ***@***.***> a
écrit :
