### ISSUE TITLE
Testing the models without training

### ISSUE THREAD

**Issue by sashavor** [punyajoy/HateXplain#3]
Hello,

Is there any way to test the models without training from scratch?

Thanks!

**Comment by punyajoy** [comment]
We will soon release the trained Bert models on [huggingface](https://huggingface.co/welcome) and update the link in the repository.
Other models are smaller in size hence can be reproduced on colaboratory also.

**Comment by sashavor** [comment]
Thank you!
I am working though your colab demo -- the models that are there, which ones are they?

**Comment by punyajoy** [comment]
I have added the code for training BiRNN-hatexplain (with attention supervision) there. Check our [paper](https://arxiv.org/abs/2012.10289) for more details. You can directly look [here](https://huggingface.co/Hate-speech-CNERG/bert-base-uncased-hatexplain) for checking the model using huggingface default inference API.

**Comment by srinivaspavan9** [comment]
> I have added the code for training BiRNN-hatexplain (with attention supervision) there. Check our [paper](https://arxiv.org/abs/2012.10289) for more details. You can directly look [here](https://huggingface.co/Hate-speech-CNERG/bert-base-uncased-hatexplain) for checking the model using huggingface default inference API.

How many classes did you choose from the dataset while fine-tuning the bert? and what are those? I need help can you please tell

**Comment by punyajoy** [comment]
There are three classes (hateful, offensive and normal). Please check the [paper](https://arxiv.org/abs/2012.10289) for distribution. We have used all three classes for training the model as shown by the [example](https://github.com/hate-alert/HateXplain/blob/master/Example_HateExplain.ipynb) also

**Comment by srinivaspavan9** [comment]
> There are three classes (hateful, offensive and normal). Please check the [paper](https://arxiv.org/abs/2012.10289) for distribution. We have used all three classes for training the model as shown by the [example](https://github.com/hate-alert/HateXplain/blob/master/Example_HateExplain.ipynb) also

Thanks for replying, I have read the paper, you have done a great job, Congrats 
I understood that you are classifying the sentences into 3 classes but how are you predicting the target group? And also need help with the dataset, so I have downloaded the dataset from the notebooks provided in the repo, but the sentences in the dataset are completely tokenized. Where can I get the untokenized one?
Thanks!

**Comment by punyajoy** [comment]
Thanks for appreciating the work. In this work, we have not done target class prediction as a task. It was only used for bias evaluation purpose. But we aim to do so in the future.

The data is tokenized to provide a token level rationale (0 or 1 indicating if a token is part of the explanation) as you can see in the dataset. Perhaps I can help you better if you can tell me the purpose of the untokenized data? In any case, a simple way would be to use the join function
`list1 = ['There", "is", "a", "cat"] ` 
`print(" ".join(list1)) `

**Comment by srinivaspavan9** [comment]
> Thanks for appreciating the work. In this work, we have not done target class prediction as a task. It was only used for bias evaluation purpose. But we aim to do so in the future.
> 
> The data is tokenized to provide a token level rationale (0 or 1 indicating if a token is part of the explanation) as you can see in the dataset. Perhaps I can help you better if you can tell me the purpose of the untokenized data? In any case, a simple way would be to use the join function
> `list1 = ['There", "is", "a", "cat"] `
> `print(" ".join(list1)) `

![image](https://user-images.githubusercontent.com/34889400/110147276-7fda1d80-7e01-11eb-8a27-879274232489.png)

I am trying to use the pre-trained bert-base-uncased-hatexplain model from huggingface/transformers to classify a simple text. Now how do I get the actual result of whether the text is offensive or not? It would be very great if you helped me with this

**Comment by srinivaspavan9** [comment]
> Thanks for appreciating the work. In this work, we have not done target class prediction as a task. It was only used for bias evaluation purpose. But we aim to do so in the future.
> 
> The data is tokenized to provide a token level rationale (0 or 1 indicating if a token is part of the explanation) as you can see in the dataset. Perhaps I can help you better if you can tell me the purpose of the untokenized data? In any case, a simple way would be to use the join function
> `list1 = ['There", "is", "a", "cat"] `
> `print(" ".join(list1)) `

Can you please help with the above code, how do I get the actual scores for the 3 classes

**Comment by kingsman142** [comment]
Figured it out. Run this:

```
from happytransformer import HappyTextClassification

happy_tc = HappyTextClassification("BERT", "Hate-speech-CNERG/bert-base-uncased-hatexplain", 3)
result = happy_tc.classify_text("this is a pretty long sentence but all i really want to say is that i hate people")
print(result)
print(result.label)
print(result.score)
```

**Comment by punyajoy** [comment]
Thanks for helping @kingsman142. I am closing the issue for now as it is well discussed in different tutorials. @srinivaspavan9, you can reopen the issue if you have some other queries.

**Comment by NirmalManoj** [comment]
@punyajoy Could you please share a tutorial or help with getting the rationale from the pretrained model on Huggingface?

**Comment by NirmalManoj** [comment]
@punyajoy Could you please share a tutorial or help get the soft rationales from the pretrained model on Huggingface?

**Comment by punyajoy** [comment]
https://github.com/hate-alert/Tutorial-ICWSM-2021. Check here.
