### ISSUE TITLE
How to get the non-tokenized dataset ?

### ISSUE THREAD

**Issue by srinivaspavan9** [punyajoy/HateXplain#4]
Is there any way to get a non-tokenized dataset or any way to convert the current dataset to a non-tokenized one?

**Comment by punyajoy** [comment]
Hi, @srinivaspavan9 as already pointed out a simple "  ".join(list_of_tokens) will convert the tokenized sentence to non tokenized version.

**Comment by srinivaspavan9** [comment]
> Hi, @srinivaspavan9 as already pointed out a simple " ".join(list_of_tokens) will convert the tokenized sentence to non tokenized version.

I have tried that but its not working.
