### ISSUE TITLE
Preprocessing specification in the Data dir

### ISSUE THREAD

**Issue by anton-sturluson** [punyajoy/HateXplain#5]
Hello, thank you for your excellent work and contribution to the community.

I noticed the following tokens in the data:
{'\<angel\>', '\<annoyed\>', '\<censored\>', '\<date\>', '\<email\>', '\<happy\>', '\<kiss\>', '\<laugh\>', '\<money\>', '\<number\>', '\<percent\>', '\<phone\>', '\<sad\>', '\<time\>', '\<url\>', '\<user\>', '\<will\>', '\<wink\>'}
But I was not able to find what they represent anywhere else. Some of them are self-explanatory (e.g. percent, time, email, URL), but the rest are not clear to me. Could you please provide more details?

**Comment by punyajoy** [comment]
Okay. These are the preprocessing tokens from https://github.com/cbaziotis/ekphrasis. So often there are different emojis in the text. Instead of directly passing them as Unicode, we thought may be text representation will be better.

**Comment by anton-sturluson** [comment]
This makes sense. Thanks!
