### ISSUE TITLE
Request for updated example and details of python version

### ISSUE THREAD

**Issue by NirmalManoj** [punyajoy/HateXplain#6]
I was trying to run the example google colab file given in the repo. At first, I got `dataclasses` cannot be found error, so I removed `dataclasses` from the requirements. After that, when running another cell that follows, I am getting an error saying `AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'`. Please have a look at the image
![image](https://user-images.githubusercontent.com/18501167/129146899-cc89a3df-9e52-4039-973b-759c8d7409d5.png)

As I understand, this is probably because the python version of colab in the example is 3.6 while the version that is available now in colab is 3.7.

I tried to run locally with a python 3.6.13 environment created using Anaconda. But I am getting the following error.
![image](https://user-images.githubusercontent.com/18501167/129147142-1de9138e-939f-44fd-845a-aad5f35cdcbf.png)

Is there an easy way to fix this so that I can run HateXplain code in google colab?

**Comment by punyajoy** [comment]
It will be better if you use the same Keras environments as mentioned in the requirements.txt. We will try to update but it is not in our immediate pipeline

**Comment by tanvirtareq** [comment]
Which python version is used ?

**Comment by punyajoy** [comment]
python version used was 3.7. But should be compatible
